version: '3.4'

services:
  edumalldocker2:
    image: edumalldocker2
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 edumall_docker.py "]
    ports:
      - 5678:5678
